# Generated by Django 4.0.4 on 2022-05-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_exam_details_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_details',
            name='created_by',
        ),
    ]
