# Generated by Django 4.0.4 on 2022-05-11 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_rename_exam_name_exam_details_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_given',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('exam', models.CharField(blank=True, max_length=200, null=True)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
