# Generated by Django 4.0.4 on 2022-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_as',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('Applicant', 'Applicant'), ('Recruiter', 'Recruiter')], max_length=100)),
            ],
        ),
    ]
