# Generated by Django 4.0.3 on 2022-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_register_as_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_as',
            name='image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to=''),
        ),
    ]
