# Generated by Django 4.0.4 on 2022-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_register_as_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_as',
            name='image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
